### ISSUE TITLE
BigSur verison

### ISSUE THREAD

**Issue by receand** [ben-z/free-sidecar#148] opened 2020-12-26 07:01 UTC
is there any way to make it work on BigSur?
thank you!

**Comment by kolya009** [comment] 2021-01-02 13:47
When trying to copy SideCore and make a backup, "cp /System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore ~/Downloads/SidecarCore.bak", terminal outputs " cp: /System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore: No such file or directory".

I'm currently trying to run this on a 2020 i5 MacBook Air on MacOS 11.1 BigSur. I may have missed something... I'm not entirely quite sure... Any help would be really appreciated!

**Comment by kmk709** [comment] 2021-01-04 11:03
Same here! I guess APPLE has changed the file path or type

**Comment by avaleriani** [comment] 2021-01-05 10:41
same issue, not able to make it work on big sur

**Comment by Revel8804** [comment] 2021-01-12 14:26
I can confirm this is not working on Big Sur. I have searched and searched through the system. Apple has made some change.

**Comment by Mr-zhaohy** [comment] 2021-01-27 01:31
same issue

**Comment by HackYe** [comment] 2021-01-29 06:57
same issue

**Comment by pozgo** [comment] 2021-01-30 14:02
Duplicate of #140

**Comment by shhschilling** [comment] 2021-02-15 15:43
Confirmed. Not working on big sur

**Comment by papucho** [comment] 2021-03-16 16:11
Any updates?

**Comment by leozvc** [comment] 2021-03-24 08:21
waiting for ....

**Comment by rtbittaker** [comment] 2021-04-01 23:35
Same issue on Big Sur 11.2.3. Early 2015 Mac Book Pro

"cp /System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore ~/Downloads/SidecarCore.bak
cp: /System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore: No such file or directory"

**Comment by sivagtr** [comment] 2021-05-02 13:56
Didn’t try in my pc.
But, 

Has anyone tried to replace with this ? 
/System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/XPCServices/DisplayMarkup.xpc

**Closed as completed** 2021-05-08 00:52 UTC
Labels: no-issue-activity
