### ISSUE TITLE
xcrun error at step 8

### ISSUE THREAD

**Issue by claxonberlin** [ben-z/free-sidecar#3] opened 2019-11-01 11:18 UTC
Hi, 

Thank you for trying to help the community left out by Apple.

I get an error at step 8:

`xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
/System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore: the codesign_allocate helper tool cannot be found or used`

Any idea on how I best proceed?

**Comment by claxonberlin** [comment] 2019-11-01 11:31
Solved.

running 

`xcode-select --install`

 did the trick for me.

**Comment by ben-z** [comment] 2019-11-01 14:06
Great! Good to hear :). I’ll mark this as a dupe of #2 if anyone still experiences issues after running `xcode-select --install`. #2 is a slightly different issue (The intermediate error message is different) but the issue tittles are similar enough.

**Closed as completed by ben-z** 2019-11-01 14:06 UTC

**Comment by jafarvillan** [comment] 2020-05-19 04:14
Hi I have this issue, my apps crashed and I can’t use any apps like safari or chrome
