### ISSUE TITLE
Unexpected side effect

### ISSUE THREAD

**Issue by Alexander-Serov** [ben-z/free-sidecar#61] opened 2020-03-26 20:03 UTC
**Mac model: MacBook Pro Early 2015 (MacBookPro12,1)
**iPad model: not important

**Mac version** (optional): Catalina 10.15.3

**Comments:**
After the update, my MacBookPro thinks that it has a touch bar. What is annoying, is that I can no longer change the behavior of the Fn keys (which I switch from time to time). Compare below.

**Before:**
<img width="649" alt="Screen Shot 2020-03-26 at 20 55 48" src="https://user-images.githubusercontent.com/22743277/77691277-e4abb780-6fa4-11ea-9936-9338747e1780.png">

**After:**
<img width="660" alt="Screen Shot 2020-03-26 at 20 38 35" src="https://user-images.githubusercontent.com/22743277/77691331-fa20e180-6fa4-11ea-80bd-30e2469f1101.png">

That was very unexpected. :))
I don't expect a solution. Just wanted to let you know in case you are not aware of the issue.

**Comment by ben-z** [comment] 2020-03-27 01:56
Thanks for the issue! I will update the README to reflect this. Dupe of #56

**Comment by ben-z** [comment] 2020-03-27 16:03
Closed by 39ddb49b499402ede3019242a6a4c876ba8895be

**Closed as completed by ben-z** 2020-03-27 16:03 UTC
