### ISSUE TITLE
picture flashing

### ISSUE THREAD

**Issue by 121sss** [ben-z/free-sidecar#1] opened 2019-10-28 15:55 UTC
hello,your patcher is really good.but still some trouble for me.
I have used sidecar-pacher before and enable sidecar successfully on my mbp2015early and ipadpro10'5,but display quality is bad on my ipadpro,the picture continues to flash.
so I wonder if I can improve display quality by using your patcher,however,after I tried,with cable,display quality never changed.
I want to ask if picture flashing is Normal by using your patch?
and if  just use your patcher(never used sidecar-patcher before)could get a close-to-original  display quality (without PICTURE FLASHING)?

**Comment by ben-z** [comment] 2019-10-28 16:07
Oh very interesting! I have MBP 2015 and iPad Air 2 and the display does not flicker at all. When you said "tried with cable" did you disconnect sidecar, connect with cable and reconnect sidecar? I'm suspecting that the screen keeps flickering is because the connection is still wireless.

Can you try Sidecar with the iPad's wifi & bluetooth off and only connect with the cable?

(Technically this is not an issue of the patcher because the patcher only enables Sidecar, doesn't deal with the performance of Sidecar)

**Comment by 121sss** [comment] 2019-10-29 05:06
I've tried with cable and disable wifi&bluetooth,but has no help with picture flicker :(

**Comment by ktpires** [comment] 2019-10-29 14:49
Same issue with macbook air (early 2015) and ipad pro 10.5"

Flicker is continuous (just working with cable, not over wifi)

**Comment by ben-z** [comment] 2019-10-29 17:28
Whoa one possible cause of this might be the computer is trying to send a high resolution desktop to the iPad Pro 10.5 but the encoder/decoder in the Mac isn’t able to keep up with such high resolution. That would explain why my setup of MBP early 2015 + iPad Air 2 does not produce flickers (iPad Air 2 has a lower resolution).

One avenue for exploration might be to lower the resolution of the iPad display. I’m not sure if macOS supports this natively. Some hacks from [here](https://everymac.com/systems/apple/macbook_pro/macbook-pro-retina-display-faq/macbook-pro-retina-display-hack-to-run-native-resolution.html) might help with this.

**Comment by Klodjan-Hoxha** [comment] 2019-11-01 14:42
How can i force SideCar to connect via USB? When i turn off wifi and bluetooth it tells me it cant connect to ipad

**Comment by ben-z** [comment] 2019-11-01 14:56
Open finder and see if your iPad shows up in the sidebar. If it does, click on it. You might need to tap “trust” on your iPad. If the iPad shows up correctly then USB Sidecar should work.

**Comment by Klodjan-Hoxha** [comment] 2019-11-01 15:04
I did that i clicked trust on my mac and ipad. This is what im working with, 2015 retina macbook pro 15" and iPad Pro 11". 

<img width="679" alt="Screen Shot 2019-11-01 at 11 03 31 AM" src="https://user-images.githubusercontent.com/53445910/68033976-3fabdd80-fc97-11e9-92f3-626c68ab34b3.png">

**Comment by Klodjan-Hoxha** [comment] 2019-11-01 15:18
i should add that sidecar does work using wifi but background keeps flickering or flashing. So i want to try connecting it wired to see if that gets rid of the problem.

**Comment by ben-z** [comment] 2019-11-01 17:51
Can you post a screenshot of the finder window showing the connected iPad?

**Comment by Klodjan-Hoxha** [comment] 2019-11-01 20:15
<img width="1060" alt="Screen Shot 2019-11-01 at 4 13 59 PM" src="https://user-images.githubusercontent.com/53445910/68053613-c1653080-fcc2-11e9-9f26-ddef1a4e6395.png">

**Comment by ben-z** [comment] 2019-11-01 21:11
Weird! One difference I see from my setup is that I'm on iPadOS 13.1.3 and you are on 13.1. Long shot but I would try updating the iPadOS if you are not intentionally holding back from updating.

**Comment by Klodjan-Hoxha** [comment] 2019-11-04 05:49
Now it just doesnt even work, i did a restore from SideCore.bak did everything from the beginning and still nothing(over wired) now it wont even connect thru wifi.

**Comment by ben-z** [comment] 2019-11-04 13:52
That's really weird! What's the error message that you got?
Also do you have kernel extensions installed on your system? USB drivers etc. I would suspect that they might interfere.

Otherwise I'm out of ideas 😢

**Comment by paulmrsn** [comment] 2019-11-21 03:09
> Whoa one possible cause of this might be the computer is trying to send a high resolution desktop to the iPad Pro 10.5 but the encoder/decoder in the Mac isn’t able to keep up with such high resolution. That would explain why my setup of MBP early 2015 + iPad Air 2 does not produce flickers (iPad Air 2 has a lower resolution).
> 
> One avenue for exploration might be to lower the resolution of the iPad display. I’m not sure if macOS supports this natively. Some hacks from [here](https://everymac.com/systems/apple/macbook_pro/macbook-pro-retina-display-faq/macbook-pro-retina-display-hack-to-run-native-resolution.html) might help with this.

Have the same issue with Macbook Pro 12,1 and iPad7,4. Lowering the resolution via third party software seems to improve flicker slightly. Also, the flicker seems to be more noticeable when the data being sent is not static (videos, or moving visual elements, even mouse movement can trigger some flicker)

Most likely the issue is what you were saying, processing power, and I can't see an easy fix for this.

**Comment by ben-z** [comment] 2019-11-21 03:19
@mmuresanpaul thanks for the feedback! Which third party software did you use to lower the resolution? I realized that easyres didn't expose additional resolutions.

**Comment by amands97** [comment] 2019-12-23 19:19
Did anyone find a solution to this problem?
Or is this caused due to the fact that the older processors don't have the capability to handle HEVC format natively?

**Closed as completed** 2019-12-29 00:06 UTC
Labels: Apple Issue, no-issue-activity

**Comment by ben-z** [comment] 2019-12-29 03:17
@amands97 That seems to be a likely cause. AFAIK there’re no solutions other than trying wired connection.
